# Generated by Django 4.1.3 on 2022-11-30 05:21

from django.db import migrations
import eventos.fields


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_video_text_image_file_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='content',
            name='order',
            field=eventos.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='order',
            field=eventos.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
